export const DEVCONTAINER_CLI_VERSION = '0.84.1'

export const BOXDOWN_CONTAINER_DEVCONTAINER_DIR = '/opt/boxdown/devcontainer'
export const BOXDOWN_CONTAINER_STATE_DIR = '/opt/boxdown/state'
export const BOXDOWN_CONTAINER_HOST_GITCONFIG_DIR = `${BOXDOWN_CONTAINER_STATE_DIR}/host-gitconfig`
export const BOXDOWN_CONTAINER_HOST_GITCONFIG_PATH = `${BOXDOWN_CONTAINER_HOST_GITCONFIG_DIR}/.gitconfig`
export const BOXDOWN_CONTAINER_SSH_DIR = `${BOXDOWN_CONTAINER_STATE_DIR}/ssh`
export const BOXDOWN_CONTAINER_SSH_PUBLIC_KEY_PATH = `${BOXDOWN_CONTAINER_SSH_DIR}/id_ed25519.pub`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR = '/opt/boxdown/agent-profile-source'
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_AGENTS_DIR = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/agents`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_CODEX_DIR = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/codex`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_CODEX_AUTH_PATH = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/codex-auth.json`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_CLAUDE_DIR = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/claude`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_CLAUDE_CREDENTIALS_PATH = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/claude-credentials.json`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_CLAUDE_CONFIG_PATH = `${BOXDOWN_CONTAINER_AGENT_PROFILE_SOURCE_DIR}/claude-config.json`
export const BOXDOWN_CONTAINER_AGENT_PROFILE_STATE_DIR = `${BOXDOWN_CONTAINER_STATE_DIR}/agent-profile`
export const BOXDOWN_CONTAINER_AGENTS_DIR = '/home/node/.agents'
export const BOXDOWN_CONTAINER_GITCONFIG_PATH = '/home/node/.gitconfig'
export const BOXDOWN_CONTAINER_CODEX_DIR = '/home/node/.codex'
export const BOXDOWN_CONTAINER_CODEX_AUTH_PATH = `${BOXDOWN_CONTAINER_CODEX_DIR}/auth.json`
export const BOXDOWN_CONTAINER_CODEX_CONFIG_PATH = `${BOXDOWN_CONTAINER_CODEX_DIR}/config.toml`
export const BOXDOWN_CONTAINER_CLAUDE_DIR = '/home/node/.claude'
export const BOXDOWN_CONTAINER_CLAUDE_CREDENTIALS_PATH = `${BOXDOWN_CONTAINER_CLAUDE_DIR}/.credentials.json`
export const BOXDOWN_CONTAINER_CLAUDE_CONFIG_PATH = '/home/node/.claude.json'
export const BOXDOWN_CONTAINER_SECRET_ENV_DIR = '/run/boxdown/secrets'
export const BOXDOWN_CONTAINER_SECRET_ENV_BOOTSTRAP = `${BOXDOWN_CONTAINER_DEVCONTAINER_DIR}/utils/secret-env-bootstrap.sh`
export const BOXDOWN_SECRET_ENV_NAMES = [
  'ANTHROPIC_API_KEY',
  'SNYK_TOKEN',
  'OP_SERVICE_ACCOUNT_TOKEN'
] as const

export const PACKAGE_NAME = 'boxdown'
